# Generated by Django 5.2.6 on 2026-02-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
